### ISSUE TITLE
TypeloadException - Method "Delete" Not Found

### ISSUE THREAD

**Issue by robcthegeek** [ronnieoverby/RavenDB-Linqpad-Driver#14]
Hi There,

I've been trying to get LINQpad talking to Raven for nearly an hour now with no win.

I keep getting the following error:

> TypeLoadException: Method 'Delete' in type 'RavenLinqpadDriver.RavenContext' from assembly 'RavenLinqpadDriver, Version=0.5.2874.0, Culture=neutral, PublicKeyToken=aaac23b83559e37f' does not have an implementation.

When trying to run a simple query:

```csharp
Query<Product>().Count()
```

I'm using the following:

- LINQpad `4.55.03`
- RavenDB Driver `0.5.2874.0`
- I've also referenced RavenDB.Client from Nuget - `3.0.3599`

Let me know if you need any more information - I'm kinda stuck :disappointed:

**Comment by ronnieoverby** [comment]
What version of the server are you trying to connect to?

**Comment by robcthegeek** [comment]
Ah - yes of course - sorry should have included this at the start:

- Server Build `#3528`
- Client Build `#3528`

**Comment by ronnieoverby** [comment]
I cannot reproduce your issue. I just installed Raven build #3599 and created a linqpad connection using the same driver version you're using (0.5.2874.0). I'm querying and storing data with no issues. I did a simple Count() like you are, but it seems to be working fine.

I tried both the x86 and Any CPU builds of Linqpad 4.55.03.

Have you had any luck?

**Comment by robcthegeek** [comment]
Hmmm... Odd.

OK - let's see if I can replicate what _you_ have to see if it's classic case of "PEBKAC" :smile: 

Let me get back to you with some info after I update my Raven Build. I'll double-check the build an CPU arch. types.

**Comment by bobmclaren** [comment]
FYI, I ran into this same problem today with the exact same error message and same server/client/LinqPad versions.  When I opened "Add connection" in LinqPad, I noticed a message stating that a third party driver was having issues.  I removed the driver entirely and then just re-added it and it's all good now.

Keep up the good work Ronnie.  This is an awesome tool for my ad-hoc Raven reporting/troubleshooting.

**Comment by ronnieoverby** [comment]
Really glad to hear that you got the issue sorted out and now I can suggest
that fix when someone reports this issue. Thanks for the encouragement!

**Comment by bobmclaren** [comment]
Okay so I may have spoken a little too soon…  ;)

After re-installing the driver, my first tab was working great, but any additional tabs I created (even cloned tabs) would not work and failed with that same exception:
TypeLoadException: Method 'Delete' in type 'RavenLinqpadDriver.RavenContext' from assembly 'RavenLinqpadDriver, Version=0.5.2874.0, Culture=neutral, PublicKeyToken=aaac23b83559e37f' does not have an implementation.

Now I have gone through the exercise again, restarting LinqPad, removing the driver, reinstalling, and now I can’t even get my first tab to work  anymore!

Any ideas would be greatly appreciated.

**Comment by ronnieoverby** [comment]
I might have to get in touch with jo albahari to see if he can shed some
light.

**Comment by bobmclaren** [comment]
I think I might have determined the issue.  I have a model class I was loading that is .NET4.5.  Your driver was built in .NET4.0.  If I start the connection with your driver first, then load my model class after that, everything is fine, but if I clone the tab, or set my model class as a default loaded assembly for new queries, I get the TypeLoadException.  Interesting behavior.  At least now we have a workaround.

**Comment by ronnieoverby** [comment]
Thanks for the leg work figuring this out. I will rebuild against 4.5 in a
day or so and create a new release.

**Comment by robcthegeek** [comment]
Just want to say thanks to you both for this!

**Comment by ronnieoverby** [comment]
Try this and let me know if it helps: 


https://github.com/ronnieoverby/RavenDB-Linqpad-Driver/releases/tag/v0.5.2874.1

**Comment by ronnieoverby** [comment]
There's another pre-release  you can check out on the releases page that targets net45 and uses the latest stable ravendb client.

**Comment by bobmclaren** [comment]
I installed the 3599 driver and it seems to be working for the most part.
A simple query like Query<Statement>().Count() successfully returns a correct response but Query<Statement>().Take(1) throws a MissingMethodException.

**Comment by ronnieoverby** [comment]
@bobmclaren what server build?

**Comment by bobmclaren** [comment]
I'm on Raven Server build 3599.

**Comment by ronnieoverby** [comment]
Check the latest release to see if this problem is fixed. #16 fixes #15 which was also a TypeLoadException.
