### ISSUE TITLE
Unable to use latest Linqpad Driver

### ISSUE THREAD

**Issue by mbp** [ronnieoverby/RavenDB-Linqpad-Driver#15]
I downloaded latest Linqpad Driver, but I get the following error when trying to query my RavenDB 3.0.3660 database:

    TypeLoadException: Method 'SideBySideExecuteIndex' in type 'RavenLinqpadDriver.RavenContext' 
    from assembly 'RavenLinqpadDriver, Version=0.7.3599.0, Culture=neutral, PublicKeyToken=aaac23b83559e37f' does not have an implementation

**Comment by kentcooper** [comment]
I had a similar problem. If your project is using a newer version of RavenDB client at least starting at 3660(maybe before that but definitely after 3599) there were some new interfaces added to IDocumentStore that have not been implemented by the driver.

**Comment by kentcooper** [comment]
Created PR to fix this you can grab the code from my fork or just wait until its merged here.

**Comment by ronnieoverby** [comment]
Fixed by #16

**Comment by simon-k** [comment]
Thank you. Fixed the problem.
